# Generated by Django 4.2.7 on 2023-12-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminsingup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('dob', models.DateField(max_length=255)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
