# Generated by Django 4.2.7 on 2023-12-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busname', models.CharField(max_length=50)),
                ('busnumber', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=50)),
                ('deparchertime', models.TimeField()),
                ('destination', models.CharField(max_length=50)),
                ('arrivaltime', models.TimeField()),
                ('seats', models.CharField(max_length=50)),
                ('busimg', models.FileField(upload_to='busimages/')),
            ],
        ),
    ]
