# Generated by Django 4.2.7 on 2023-12-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_bus_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_details',
            name='ticketprice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
