# Generated by Django 4.2.7 on 2023-12-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_bus_details_ticketprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsingup',
            name='dob',
        ),
        migrations.AddField(
            model_name='adminsingup',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
