# Generated by Django 4.2.7 on 2023-12-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_adminsingup_dob_adminsingup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_details',
            name='availableseats',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
